name: gpi_ling5
#gpi_type: "NeighbourAttention"
#gpi_type: "FeatureAttention"
gpi_type: "Linguistic"
nof_iterations: 10000
learning_rate: 0.0001
learning_rate_steps: 100
learning_rate_decay: 0.5
load_model_name: "gpi_ling2_best_module.ckpt"
use_saved_model: True
batch_size: 200
rnn_steps: 2
predicate_pos_neg_ratio: 10
lr_object_coeff: 4
including_object: True
layers: [500, 500, 500]
reg_factor: 0.0
gpu: 1

